name: Build Container Image

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-and-push:
    name: build and push to ghcr
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Path to dockerfile (current directory).
          push: true # Push to registry.
          tags: |
            ghcr.io/${{ github.repository_owner }}/tt-http-app:latest
            ghcr.io/${{ github.repository_owner }}/tt-http-app:${{ steps.vars.outputs.sha_short }}
          platforms: linux/amd64,linux/arm64
