name: Checks

on:
  push:
    branches: ["main"]

jobs:
  typos:
    runs-on: ubuntu-latest
    name: spell check with typos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Run typos command
        shell: nix shell nixpkgs#typos --quiet --command bash {0}
        run: sh ./scripts/check-typos.sh
